ترجمه مفهوم کار انجام شده
Delpak/Vidamouz pull request #1
Opened 2018-04-07 15:31 UTC by mirsaeedi

ترجمه انجام شده ولی چند جایی هست که من نتونستم معادل های مناسبی واسه بعضی از کلمات پیدا کنم

2018-04-07 15:34 UTC, mirsaeedi commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
>  I capture them and what I like to call a narrative which is my artifact to express done
مثلا در اینجا چه کلمه ای باید جایگزین نریتیو شود که گویا و مفهوم باشد

2018-04-07 15:35 UTC, mirsaeedi commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +در این تیم ها وضعیتِ پیشرفت کار  توسط نمودار های x نمایش داده می شود
یا برای این نمودار ها چه عنوانی را باید به کار برد؟

2018-04-07 17:19 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
>  I capture them and what I like to call a narrative which is my artifact to express done
از بین دیکشنری های انلاین این سایت کارگشاست

http://www.parsi123.com/?word=narrative
همچنین سایت واچک
Http://vachak.ir
اما پیشنهاد من:
 آنها را گردآوری کردم و مایلم دست آوردم را روایتی بنامم از تعریف کار انجام شده.

2018-04-07 20:53 UTC, mirsaeedi commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
>  I capture them and what I like to call a narrative which is my artifact to express done
از منظر لغوی روایت ترجمه درست و خوبی هست ولی نمی دونم که اینجا می تونه بیانگر موضوع باشه. مخصوصا که اینجا می خواد مفهوم داستان کاربری رو بیاد و با مفهوم پرکاربر نریتیو مقایسه کنه

2018-04-07 20:54 UTC, mirsaeedi commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +در این تیم ها وضعیتِ پیشرفت کار  توسط نمودار های x نمایش داده می شود
می تونیم مثه ترجمه مهرداد از عنوان برن دان استفاده کنیم

2018-04-07 20:58 UTC, mirsaeedi commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
>  I capture them and what I like to call a narrative which is my artifact to express done
منظورم این هست که آیا "روایت" می تونه جا بیفته در زبان شخص فارسی زبان برای این مفهوم؟

2018-04-07 23:53 UTC, Delpak requested changes
۲۰ فریم اول را بازنگری کردم

2018-04-07 23:53 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +تا معیاری داشته باشند که بشود تصمیم گرفت که یک کار چه وقتی به معنی واقعی به اتمام رسیده است
تعریفی که کمک می‌کند تا بدانند که چه زمانی کارشان تکمیل شده است

2018-04-07 23:53 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +می خواهیم در مورد این صحبت کنیم که تیم های چابک چگونه می توانند به تعریفی از کار انجام شده دست پیدا کنند
می‌خواهیم به این موضوع بپردازیم که تیم‌های چابک چگونه به تعریفی از کار انجام شده می‌رسند

2018-04-07 23:53 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +تعریف "کار انجام شده" بدین معنی است که واقعا کار دیگری برای آن تسک نباید انجام شود، حتی در رابطه با اجرایی کردنِ آن در محیط عملیات
«انجام شده» یعنی اینکه لازم نیست هیچ کار دیگری انجام شود. حتی یک کار جزیی برای استقرار در محیط عملیاتی

2018-04-07 23:53 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +تعریف "کار انجام شده" بدین معنی است که واقعا کار دیگری برای آن تسک نباید انجام شود، حتی در رابطه با اجرایی کردنِ آن در محیط عملیات
در زیرنویس کردن باید به طول جمله توجه کرد. مدت زمانی که جمله روی ویدیو نشان داده می شود ثابت است و چندان قابل تغییر نیست. در این زمان ثابت هر چقدر متن کوتاه تر باشد، بیننده سریعتر میتواند آن را بخواند که از ویدیو جا نماند

2018-04-07 23:53 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
>  while agile teams come to an agreement on the definition of done
هنگامی که تیم‌های چابک می‌خواهند در خصوص تعریف کار انجام شده به توافق برسند

2018-04-07 23:53 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +آن ها با دقت بیشتری در مورد کارهایی که باید انجام دهند گفتگو و بحث می کنند
با طرح این سوال که چه کارهایی باید انجام شود، یک طوفان فکری را آغاز می‌کنند

2018-04-07 23:53 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +دقیقا کارهای لازم برای تکمیل و عملیاتی شدن یک داستان کاربری و یا یک ویژگی کارکردی را مشخص می کنند
و چه [دست ساخته‌هایی](http://www.parsi123.com/?word=artifact) باید ساخته شوند تا یک داستان کاربری یا یک قابلیت به بهره‌برداری برسد

2018-04-07 23:53 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +آن ها مشخص خواهند کرد که چه چیزی را می توانند و یا نمی توانند انجام دهند
آنها تشخیص می‌دهند که چه چیزی انجام شدنی و چه چیزی انجام نشدنی‌ است

2018-04-07 23:53 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +آن ها به دقت مسائلی را که سد پیش روی کارهای انجام نشدنی هستند، فهرست می کنند
همچنین موانع پیش روی کارهای انجام نشدنی را ثبت می‌کنند

2018-04-07 23:53 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +در نهایت هم، همگی بر سر اینکه چه چیزی قابل انجام هست توافق می کنند
سپس درباره کارهای انجام شدنی به یک نظر مشترک می‌رسند

2018-04-07 23:53 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +اهمیت دیگر تعریف "کار انجام شده" این می باشد که می توانیم با آن میزان پیشرفت کار را اندازه بگیریم
تعریف کار انجام شده برای تیمهای چابک از این بابت مهم است، که می‌توانند پیشرفت کارشان را با دقت اندازه‌گیری کنند

2018-04-07 23:53 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +همه اعضای تیم در کنار مشتری و ذینغ
همه تیم همراه با جین، که سرپرست تیم منابع انسانی و نیز مشتری این محصول است

2018-04-07 23:53 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +در به توافق رسیدن و تعریف "کار انجام شده" شریک و دخیل هستند و به ندرت آن را تغییر می دهند
irregularly در متن اشتباه آمده است
regularly  درست است
مشغول میشوند تا تعریفی برای کار انجام شده ارایه کنند
ضمنا آنها برای به روز نگه داشتن این تعریف، مرتبا ملاقات برگزار می‌کنند

2018-04-07 23:53 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +ایشون سوزان هستند، تحلیل گر تیم
ایشان سوزان است که به عنوان تحلیلگر کسب و کار در تیم فعالیت می‌کند

2018-04-07 23:53 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +او توضیح می دهد که از نظرش تعریف "کار انجام شده" چیست تا همه بتوانند به یک درک مشترک برسند
او **برای تیم** توضیح می‌دهد که از نظرش تعریف "کار انجام شده" چیست تا همه بتوانند به درک مشترکی برسند

2018-04-07 23:53 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +کار انجام شده باید برای مشتری و یا مدیر محصول ملموس بوده و رضایت آن ها را جلب کند
**اساسا** منظور از انجام شده این است که مشتری و مدیر محصول از آنچه که تحویل گرفته‌اند خوشحال باشند

2018-04-07 23:53 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +در واقع آن ها می توانند مهر تایید نهایی را بر کار بزنند
و تایید کنند که همه داستانهای کاربری انجام شده است

2018-04-07 23:53 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +او در ادامه تعریف "کار انجام شده" اضافه می کند که
او در ادامه می‌گوید

2018-04-08 07:21 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
>  I capture them and what I like to call a narrative which is my artifact to express done
به نظرم گوینده میخواد بگه که تعریفی که تا الان از کار انجام شده صورت گرفته، بیشتر شبیه یک روایت غیررسمی هستش.

2018-04-13 15:15 UTC, Delpak approved these changes

2018-04-13 15:46 UTC, Delpak approved these changes

2018-04-14 16:44 UTC, Delpak approved these changes

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +در فرایند پیاده سازی یک کار، می توانیم گام های کوچک و مشخصی را تصور کنیم
از زمانی که داستان کاربر وارد فرآیند توسعه می‌شود و در مسیر توسعه، می‌تونید چندین نقطه کنترلی مشخص کنید

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
>  since the story goes through a development process, you can identify smaller checkpoints of done along the way
since the story goes through a development process, you can identify small checkpoints of done along the way

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +مثلا، فقط باید پس از اینکه من واقعا به حد کافی معیارهای پذیرش و فرضیات یک داستان کاربری را مشخص کردم
مثلا خودِ من، فقط بعد از اینکه به حد کافی، شرایط پذیرش و فرضیات یک داستان کاربر را مشخص کردم

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +آن را به توسعه دهنده محول کنیم
توسعه‌دهنده می‌تونه اون رو برای شروع به دست بگیره

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +ازونجایی که همه این ها در تعریف داستان کاربری جا نمی شوند – چون داستان های کاربری معمولا خلاصه هستند -
چون نمیشه همه این اطلاعات رو روی یک کارت داستان کاربر جا داد

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +من آن ها در چیزی به تحت عنوان ایکس  ثبت می کنم
همه‌شون رو جمع می‌کنم و اسمشون رو میذارم روایتی از تعریف «انجام شده»

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +که می تواند یک  طرح ساده از یک فرم باشد
این میتونه به شکل یک طرح اولیه از فرم فیدبک باشه
-مترجم: فرم فیدبک یک نمونه از فرمهای اپلیکیشن است

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +یا یک اسکرین شات
یا عکسی از یک نمونه اولیه باشه

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +و یا حتی مسائل و جزییات فنی ایی باشد که باید در نظر گرفته شود
و یا حتی شامل بعضی مسایل فنی‌ای باشه که باید بهشون توجه بشه

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +تام – که توسعه دهنده می باشد – توضیحات را ادامه می دهد
تام (توسعه دهنده) بحث را ادامه می‌دهد

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +برای اینکه کار را بتوانیم تمام کنیم
برای اینکه داستان کاربری را به مرحله «انجام شده» نزدیکتر کنیم

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +کدی که من نوشته ام باید توسط شخص دیگری هم بازبینی شود
یک توسعه‌دهنده دیگه هم باید تیکه کارهای من رو بازنگری کنه

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +و باید بتوانیم آن را به درستی و بدون مشکل با نسخه کنونی سیستم یکپارچه کنیم
و کار من با نسخه‌ی فعلی راه حل، به درستی یکپارچه بشه

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +دِمیِن ادامه می دهد که
دِمیِن می‌گوید

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +موضوع دیگری که باید برای نهایی کردن یک کار مد نظر داشته باشیم
موضوع دیگه‌ای که در حین تکمیل داستان کاربری باید وارسی بشه

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +این است که مطمئن باشیم، بازخوردی را که پیشتر از مشتری گرفته ایم پیاده سازی کرده ایم
اینه که مطمن باشیم که بازخورد دریافت شده از کاربران رو پیاده‌سازی کرده‌ایم

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +تا مطمئن شویم در پیاده سازی داستان کاربری رضایت کاربر را جلب می کنیم
و این باعث میشه مطمن بشیم که این داستان برای کاربر، تجربه رضایت بخشی رو ایجاد میکنه

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +بالاتر از همه این ها، "کار انجام شده" یعنی کاری که مشتری یا مدیر محصول آن را بررسی کرده و تایید کرده است
مهمتر از همه، «انجام شده» یعنی اینکه مشتری و مالک محصول، این داستان رو تست و تایید کردند

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +در حقیقت، لازمه اتمام یک کار آن است که بتواند تمام تست هایی را که توسط تحلیلگر طراحی شده پاس کند
در واقع داستان کاربر وقتی تکمیل میشه که همه تستهایی که بر اساس شرایط پذیرش ایجادشون کردیم، با موفقیت پاس بشن

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +این مضوع حتی تست های کارایی هم شامل می شود
حتی تستهای کارایی (پرفورمنس) هم شاملش میشه

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +که به زبان ساده یعنی اندازه گیری زمان پاسخ سیستم وقتی تعداد درخواست ها در بازه ای کوتاه بسیار بالا می رود
یعنی بسنجیم که وقتی کاربران زیادی به طور هم‌زمان از سیستم استفاده می‌کنند، مدت زمان پاسخگویی سیستم چقدره

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +و این از نگاهِ ما توسعه دهنده ها معنی کار انجام شده است
این تعریفیِ که ما توسعه دهنده‌ها از «انجام شده»‌ داریم

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +اما جِن از نظر تو که مدیر محصول هستی، کار تعریف شده یعنی چی؟
جن نظر تو به عنوان مالک محصول چیه؟

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +خب! به عنوان مشتری کار از نظر من وقتی انجام شده که همه کاربران سیستم
جن: ببین دَمیِن، من به عنوان یه مشتری وقتی میگم کار انجام شده که کل کارمندان شرکت

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +با محصولی مواجه باشند که استفاده آسان و بی دردسری داشته باشد
سیستمی داشته باشن که کار باهاش راحت باشه

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +یعنی بتوانند به راحتی همه امورشان را انجام دهند
که با اون بتونن فرمهای سنجش کارایی رو پر کنند و بازخوردها رو داشته باشن

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +عضو دیگر می گوید که
حالا بیل (عضو تیم) یک جمع بندی از بحث تیم ارایه می‌دهد

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +خب بیاید در مورد اینکه تعریف "کار انجام شده" برای ما چی هست، جمع بندی بکنیم
بیل: خب ببینیم که به چه نتیجه‌ای در مورد تعریف «کار انجام شده» رسیدیم

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +فارغ از اینکه با یک داستان کاربری رو به رو باشیم
چه در مورد یک داستان کاربری صحبت کنیم

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +یک قابلیت کاربردی یا یک چرخه از یک اسپرینت
و چه درمورد یک قابلیت یا یک چرخه‌ی تکرار

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +یا حتی در مقیاس بزرگتر با یک نسخه ریلیز شده از محصول مان
و یا اینکه منظورمون یک نسخه از محصول یا سیستم باشه

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +کارِ ما زمانی تمام شده که ما به عنوان یک تیم واحد
کار وقتی تکمیل شده که ما به عنوان یک تیم

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +عمیقا مطمئنیم که به این زودی سمت تغییر و ویرایش آن کار نخواهیم رفت – چون کاری برای انجام دادن نمانده -
واقعا یقین داشته باشیم که دیگه لازم نیست کار دیگه‌ای براش انجام بشه (چون همه کارهای آن تکمیل شده)

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +در این سری از گفتگو ها
در این گفتگوی چابکی در عمل

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
>  in this agile and practice talk
in this agile in practice talk

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
>  this progress is displayed in burnt charts
this progress is displayed in burn charts

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +تیم های چابک نیاز دارند به تعریف "کار انجام شده" دست پیدا کنند تا بتوانند از میزان پیشرفت و وضعیت کار آگاه باشند
آموختید که تیمهای چابک برای رصد پیشرفت کارشان، بایستی به تعریف مشترکی از «کار انجام شده»‌ برسند

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +در این تیم ها وضعیتِ پیشرفت کار  توسط نمودار های x نمایش داده می شود
پیشرفتی که به شکل «نمودار کار باقی‌مانده» (Burn Chart) نمایش داده شده است

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
>  and agile metric that is a topic for another time
an agile metric that is a topic for another time

2018-04-14 16:44 UTC, Delpak commented on Agile in Practice Definition of Done/Agile in Practice_ Definition of Done.srt
> +که این نمودار را به همراه باقی سنجه های چابکی در زمانی دیگر معرفی می کنیم
نموداری که یکی از شاخصهای چابکی است و در زمان دیگری به این موضوع می‌پردازیم

2018-04-14 19:01 UTC, Delpak commented
بازنگری شد و نظرم به صورت ریویو ثبت شد.

2018-04-14 19:02 UTC, merged