ترجمه تا شماره 46
Delpak/Vidamouz pull request #10
Opened 2018-04-19 21:46 UTC by masoud-bahrami

2018-04-23 20:34 UTC, Delpak requested changes
۲۵ فریم اول بازنگری شد.

2018-04-23 20:34 UTC, Delpak commented on GOTO 2014 • Microservices • Martin Fowler/GOTO+2014+Microservices+Martin+Fowler.srt
> +خب در سال گذشته در مورد مایکروسرویس ها زیاد صحبت شد
زمان جمله
Present perfect continuous
است. 
پینشهاد:
`خب در سال گذشته درباره ریزخدمتها (مایکروسرویسها)‌ زیاد صحبت شده`

2018-04-23 20:34 UTC, Delpak commented on GOTO 2014 • Microservices • Martin Fowler/GOTO+2014+Microservices+Martin+Fowler.srt
> +و مطالب زیادی هم در توییتر می‌بینم که نشانه‌ی علاقه به گفتگو درباره این موضوع است
> و حجم انبوهی از مطالبی که در توییتر می‌بینم، نشانه تمایل به گفتگو در این‌باره است

2018-04-23 20:34 UTC, Delpak commented on GOTO 2014 • Microservices • Martin Fowler/GOTO+2014+Microservices+Martin+Fowler.srt
> +و من برای مدت بیشتری در مورد مایکروسرویس ها شنیدم
البته این موضوعیه که من کمی قبلتر از این‌ها در موردش شنیدم

2018-04-23 20:34 UTC, Delpak commented on GOTO 2014 • Microservices • Martin Fowler/GOTO+2014+Microservices+Martin+Fowler.srt
> +همکاران و دوستان مختلفم در دو سه سال گذشته در مورد مایکروسرویس ها صحبت کردند
خب در دو سه سال اخیر بعضی از دوستانم در این مورد صحبت کرده بودند

2018-04-23 20:34 UTC, Delpak commented on GOTO 2014 • Microservices • Martin Fowler/GOTO+2014+Microservices+Martin+Fowler.srt
> +و چالش اصلی برای من تلاش و شناخت صحیح اینکه مایکروسرویس ها چه هستند؟ بود
چالشی که من باهاش مواجه بودم این بود که، خوب بفهمم مایکروسرویس‌ها واقعا چی هستند

2018-04-23 20:34 UTC, Delpak commented on GOTO 2014 • Microservices • Martin Fowler/GOTO+2014+Microservices+Martin+Fowler.srt
> +وقتی افراد در مورد مایکروسرویس ها صحبت می کنند دقیقا منظور آنها چیست؟
کسانی که در مورد مایکروسرویسها صحبت می‌کنند واقعا منظورشون چیه؟

2018-04-23 20:34 UTC, Delpak commented on GOTO 2014 • Microservices • Martin Fowler/GOTO+2014+Microservices+Martin+Fowler.srt
> +و می دونید، چه موقع باید استفاده از این تکنیک را بررسی کنیم؟
و اینکه در چه شرایطی استفاده از این تکنیک رو مدنظر قرار بدیم؟

2018-04-23 20:34 UTC, Delpak commented on GOTO 2014 • Microservices • Martin Fowler/GOTO+2014+Microservices+Martin+Fowler.srt
> +جدید است یا نیست؟ آیا ازش استفاده کنیم؟ استفاده نکنیم؟ و در وهله ی اول اصلا مایکروسرویس ها چی نیستند؟
موضوع جدیدی‌ است یا نه؟ استفاده کنیم یا نه؟ و قبل از همه‌ی اینها، اصلا مایکروسرویس‌ها چی نیستند؟

2018-04-23 20:34 UTC, Delpak commented on GOTO 2014 • Microservices • Martin Fowler/GOTO+2014+Microservices+Martin+Fowler.srt
> +منظورم اینه که ایده اولیه کاملا روشن و قابل درک است
یعنی اینکه ایده اصلی خیلی شفاف و واضحه

2018-04-23 20:34 UTC, Delpak commented on GOTO 2014 • Microservices • Martin Fowler/GOTO+2014+Microservices+Martin+Fowler.srt
> +شما مایکروسرویس ها را با چیزی که به عنوان برنامه تکی سنتی در نظر گرفته می شود مقایسه می کنید
به راحتی اونو مقابلِ اپلیکشینهای مرسوم یک-تکه (مونولیت) در نظر می‌گیرید

2018-04-23 20:34 UTC, Delpak commented on GOTO 2014 • Microservices • Martin Fowler/GOTO+2014+Microservices+Martin+Fowler.srt
> +یک برنامه تکی به این معنی است که شما قابلیت های مختلفی دارید
منظور از اپلیکشین یک-تکه اینه که قابلیتهای متنوع

2018-04-23 20:34 UTC, Delpak commented on GOTO 2014 • Microservices • Martin Fowler/GOTO+2014+Microservices+Martin+Fowler.srt
> +موارد مختلفی که می خواهید پیاده کنید
و چیزهایی که می‌خواید ارایه کنید

2018-04-23 20:34 UTC, Delpak commented on GOTO 2014 • Microservices • Martin Fowler/GOTO+2014+Microservices+Martin+Fowler.srt
> +و همه ی آن قابلیت ها را در یک برنامه مشابه قرار می دهید
همه‌شون رو در یک اپلیکشین قرار می‌دید

2018-04-23 20:34 UTC, Delpak commented on GOTO 2014 • Microservices • Martin Fowler/GOTO+2014+Microservices+Martin+Fowler.srt
> +که معمولا در یک فرآیند اجرا می شود
که معمولا هم در یک پردازشگر اجرا می‌شوند

2018-04-23 20:34 UTC, Delpak commented on GOTO 2014 • Microservices • Martin Fowler/GOTO+2014+Microservices+Martin+Fowler.srt
> +و به این برنامه به عنوان یک موجودیت واحد فکر می کنید
و اونو یک چیز در نظر می‌گیرید

2018-04-23 20:34 UTC, Delpak commented on GOTO 2014 • Microservices • Martin Fowler/GOTO+2014+Microservices+Martin+Fowler.srt
> +اما پیشنهاد مایکروسرویس
اما در رویکرد مایکروسرویس

2018-04-23 20:34 UTC, Delpak commented on GOTO 2014 • Microservices • Martin Fowler/GOTO+2014+Microservices+Martin+Fowler.srt
> +و دستورالعمل اصلی آن؛ تلاش برای برداشتن هر کدام از این قابلیت ها و قرار دادن آنها در فرآیندهای مستقل است
و دستورالعملهای کمکی اون، سعی بر اینه که هر کدوم از این قابلیتها جدا بشه و به پردازشگرهای مجزا سپرده بشه

2018-04-23 20:34 UTC, Delpak commented on GOTO 2014 • Microservices • Martin Fowler/GOTO+2014+Microservices+Martin+Fowler.srt
> +و بجای اینکه فقط یک فرآیند داشته باشیم؛ این شبکه از فرآیندها را داریم
و به جای داشتن یک پردازشگر، شبکه‌ای از پردازشگرها رو داریم که با هم در ارتباط هستند

2018-04-23 20:34 UTC, Delpak commented on GOTO 2014 • Microservices • Martin Fowler/GOTO+2014+Microservices+Martin+Fowler.srt
> +بسیاری از افراد دوست دارند از مثال خط فرمان یونیکس استفاده کنند
خیلی‌ها دوست دارند از مثالِ خط فرمان یونیکس، استفاده کنند

2018-04-23 20:34 UTC, Delpak commented on GOTO 2014 • Microservices • Martin Fowler/GOTO+2014+Microservices+Martin+Fowler.srt
> +در یونیکس اگر بخواهید لیستی از فایل ها را در دایرکتوریتان مرتب کنید، ممکن است از 2 یا 3 برنامه متفاوت استفاده کنید
در یونیکس اگر بخواید لیست مرتب شده‌ای از فایلهای یک پوشه رو داشته باشید، ممکنه از ۲ یا ۳ برنامه استفاده کنید

2018-04-23 20:34 UTC, Delpak commented on GOTO 2014 • Microservices • Martin Fowler/GOTO+2014+Microservices+Martin+Fowler.srt
> +و آنها را با هم درون یک خط لوله قرار دهید تا این برنامه ها را اجرا کند
و اونها رو باهم در یک خط لوله (Pipeline) قرار بدید تا این کار رو انجام دهند

2018-04-23 20:34 UTC, Delpak commented on GOTO 2014 • Microservices • Martin Fowler/GOTO+2014+Microservices+Martin+Fowler.srt
> +قرار دادن قابلیت ها در سرویس های مجزا همچنین منجر به توزیع شدگی می شود
این رویکرد، منجر به توزیع پذیری هم میشه

2018-04-23 20:34 UTC, Delpak commented on GOTO 2014 • Microservices • Martin Fowler/GOTO+2014+Microservices+Martin+Fowler.srt
> +اگر شما یک برنامه تکی داشته باشید با قالب بندی های موثر در برنامه تکی و قرار دادن آن در چندین ماشین؛ آنرا مقیاس می کنید
افزایش مقیاس یک اپلیکشین یک-تکه رو مثل بیسکویت قالب زده شده انجام می‌دید. قالب‌ها (که کاملا شبیه هم هستند و در اینجا منظور کل اپلیکیشن است)‌ روی ماشینهای مجزا قرار می‌گیرند

2018-04-23 20:34 UTC, Delpak commented on GOTO 2014 • Microservices • Martin Fowler/GOTO+2014+Microservices+Martin+Fowler.srt
> +اما با مایکروسرویس ها؛ رویکردهای منعطف تری دارید چون می توانید
اما در مایکروسرویسها با رویکرد منعطف‌تری مواجه هستید چون می‌توانید

2018-04-23 20:54 UTC, Delpak requested changes
فریمهای ۲۶ و ۲۷ بازنگری شد

2018-04-23 20:54 UTC, Delpak commented on GOTO 2014 • Microservices • Martin Fowler/GOTO+2014+Microservices+Martin+Fowler.srt
> +در نتیجه در صورتی که سرویسی بار بیشتری نسبت به بقیه دریافت کند؛ می توانید کپی های بیشتری از آن ایجاد کنید
و خب اگر سرویسی به نسبت بقیه سرویس‌ها بار بیشتری دریافت کنه، میشه از اون سرویس کپی‌های بیشتری ساخت

2018-04-23 20:54 UTC, Delpak commented on GOTO 2014 • Microservices • Martin Fowler/GOTO+2014+Microservices+Martin+Fowler.srt
> +این یک دید اجمالی اولیه است
خب یه مرور خیلی سرسری کردیم

2018-04-26 17:38 UTC, masoud-bahrami commented on GOTO 2014 • Microservices • Martin Fowler/GOTO+2014+Microservices+Martin+Fowler.srt
> +همکاران و دوستان مختلفم در دو سه سال گذشته در مورد مایکروسرویس ها صحبت کردند
خوب توی این جمله اضافه است

2018-04-26 17:42 UTC, masoud-bahrami commented on GOTO 2014 • Microservices • Martin Fowler/GOTO+2014+Microservices+Martin+Fowler.srt
> +منظورم اینه که ایده اولیه کاملا روشن و قابل درک است
جمله ی i mean از ترجمه حذف شده. چون داره از نظر خودش میگه که ایده اصلی خیلی شفاف است!

2018-04-26 21:20 UTC, closed without merging