translate first 15 lines
Delpak/Vidamouz pull request #8
Opened 2018-04-16 20:30 UTC by mostafavtp

2018-04-17 08:31 UTC, Delpak requested changes
بازنگری ۱۵ خط اول انجام شد.
در دو مورد مجبور شدم که خطوط متن اصلی را دستکاری یا ترکیب کنم.

2018-04-17 08:31 UTC, Delpak commented on Agile in Practice Test Driven Development/Agile+in+Practice+Test+Driven+Development.srt
>  in this Agile and practice talk
in this Agile in practice talk

2018-04-17 08:31 UTC, Delpak commented on Agile in Practice Test Driven Development/Agile+in+Practice+Test+Driven+Development.srt
> +در این آموزش عملی
در این گفتار از سری گفتارهای «چابکی در عمل»

در واقع این ویدیوها، یک سری ۲۰ ویدیویی هستند که در هر کدام به موضوعی می‌پردازند.

2018-04-17 08:31 UTC, Delpak commented on Agile in Practice Test Driven Development/Agile+in+Practice+Test+Driven+Development.srt
> +که معمولا با عنوان TDD شناخته می‌شود
به نظر در اینجا منظور از Commonly عموما است.

2018-04-17 08:31 UTC, Delpak commented on Agile in Practice Test Driven Development/Agile+in+Practice+Test+Driven+Development.srt
> +TDD یک نظام توسعه نرم‌افزار است
برای discipline دستورالعمل را مناسبتر می‌دانم 

> تی.تی.دی دستورالعملی برای توسعه نرم افزار است که

2018-04-17 08:31 UTC, Delpak commented on Agile in Practice Test Driven Development/Agile+in+Practice+Test+Driven+Development.srt
> +TDD یک نظام توسعه نرم‌افزار است
یکی از ریزه کاریهای زیر نویس این است که اگر بیینده باید منتظر ادامه جمله در تصویر بعدی باشد، به نحوی ارتباط جمله ها را نشان دهیم

مثلا در آخر جمله از حرف ربط «که» استفاده کنیم.
برای همین کلمه where از جمله بعدی را به جمله قبلی می آورم

2018-04-17 08:31 UTC, Delpak commented on Agile in Practice Test Driven Development/Agile+in+Practice+Test+Driven+Development.srt
>  where developers write automated test cases for enhancements
`developers write automated test cases for enhancements`

2018-04-17 08:31 UTC, Delpak commented on Agile in Practice Test Driven Development/Agile+in+Practice+Test+Driven+Development.srt
>  TDD is a software development discipline
`TDD is a software development discipline where `

2018-04-17 08:31 UTC, Delpak commented on Agile in Practice Test Driven Development/Agile+in+Practice+Test+Driven+Development.srt
>  or new features before they write any code
لازم است دو جمله به هم وصل شوند

در این شرایط برای جمله دوم هیچ متنی نوشته نشود
فقط شماره فریم و تایم فریم گذاشته شود
در بازبینی نهایی این خطوط خالی حذف می‌شوند

2018-04-17 08:31 UTC, Delpak commented on Agile in Practice Test Driven Development/Agile+in+Practice+Test+Driven+Development.srt
>  where developers write automated test cases for enhancements
`developers write automated test cases for enhancements or new features before they write any code `

2018-04-17 08:31 UTC, Delpak commented on Agile in Practice Test Driven Development/Agile+in+Practice+Test+Driven+Development.srt
>  where developers write automated test cases for enhancements
بر آن اساس، توسعه دهندگان قبل از کد نویسی برای توسعه یا افزودن قابلیت جدید، باید تست‌های موردی بنویسند

2018-04-17 08:31 UTC, Delpak commented on Agile in Practice Test Driven Development/Agile+in+Practice+Test+Driven+Development.srt
> +اصل اولیه TDD این است که
منطق ساده‌ی تی.تی.دی این است که

2018-04-17 08:31 UTC, Delpak commented on Agile in Practice Test Driven Development/Agile+in+Practice+Test+Driven+Development.srt
>   is that you begin by writing a failing test
`is that you begin by writing a failing test for the simplest piece of functionality that you need to implement`

دو جمله ادغام شد

2018-04-17 08:31 UTC, Delpak commented on Agile in Practice Test Driven Development/Agile+in+Practice+Test+Driven+Development.srt
>   is that you begin by writing a failing test
ابتدا برای جزیی ساده‌‌ از عملکردی که می‌خواهید پیاده‌سازی کنید، تستی می‌نویسید که پاس نمی‌شود

2018-04-17 08:31 UTC, Delpak commented on Agile in Practice Test Driven Development/Agile+in+Practice+Test+Driven+Development.srt
> + سپس ساده ترین کد را برای پاس شدن این آزمون می‌نویسید
و بعد ساده‌ترین کد ممکن، برای پاس شدن آن تست را می‌نویسید

2018-04-17 08:31 UTC, Delpak commented on Agile in Practice Test Driven Development/Agile+in+Practice+Test+Driven+Development.srt
> + وقتی این کار انجام شد
وقتی این کار انجام شد (تست پاس شد)

2018-04-17 08:31 UTC, Delpak commented on Agile in Practice Test Driven Development/Agile+in+Practice+Test+Driven+Development.srt
> + کد را برای بهتر شدن بازنویسی می‌کنید(ریفکتور)
روی کد جدید کار می‌کنید و آن را بازسازی می‌کنید تا به شکل بهتری درآید

2018-04-17 08:31 UTC, Delpak commented on Agile in Practice Test Driven Development/Agile+in+Practice+Test+Driven+Development.srt
> + پس چرا همه این کارها را انجام می دهید؟
خب! چرا این همه کار کنیم؟

2018-04-18 21:49 UTC, mostafavtp commented on Agile in Practice Test Driven Development/Agile+in+Practice+Test+Driven+Development.srt
>  or new features before they write any code
آیا لازمه زمان انتها هم دز جمله اول اصلاح بشه؟
یا این هم در بازبینی نهایی اعمال میشه؟

2018-04-19 12:30 UTC, merged